baseURL = "https://gizemsoylutr.github.io/"
languageCode = "en-us"
title = "Gizem Nur Soylu"

# Copyright
copyright = "Â© 2025 Gizem Nur Soylu"

# Meta description
[params]
  description = "SAP Cloud Technical Architect - Think simple, do simple"
  author = "Gizem Nur Soylu"

[module]
  [[module.imports]]
    path = "github.com/hugo-toha/toha/v4"

publishDir = "docs"
